version: "3"
services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    user: root
    volumes:
      - ./dev_data:/remote_data # mount
      #- ./nginx:/etc/nginx/conf.d
    ports:
      - 44444:22 # SSH PORT
      - 2525:25 # SMTP PORT
      - 80:80 # HTTP PORT
      - 11110:110 # POP3 PORT
      - 443:443 # HTTPS PORT
      - 53306:3306 # MariaDB PORT
    command: bash -c "service nginx start && service ssh start && service mariadb start && tail -f /dev/null"
